services:
  neurosync:
    build:
      dockerfile: Dockerfile
    container_name: NeuroSync
    networks:
      - matrix-net
    ports:
      - 8080:8080
    volumes:
      # Mount the host's .env file into the container's working directory
      # This makes changes inside the container persist on the host
      - ./.env:/app/.env

networks:
  matrix-net:
    external: true