networks:
  matrix-net:
    external: true

services:
  neurosync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NeuroSync
    env_file:
      - .env
    volumes:
      - ./crypto_data:/app/crypto_store
      - ./.env:/app/.env
      - ./data:/app/data
    networks:
      - matrix-net
    ports:
      - 8080:8080